### ISSUE TITLE
JSON error when calling `Parser.from_file`

### ISSUE THREAD

**Issue by ghost** [beanieboi/ffprober#79]
When I try to run this in `irb` using the method `Parser.from_file("/path/to/video.mkv")` I get some of the FFProbe stdout and then this error:

```
JSON::ParserError: A JSON text must at least contain two octets!
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:156:in `initialize'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:156:in `new'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:156:in `parse'
	from /Library/Ruby/Gems/2.3.0/gems/ffprober-0.5.2/lib/ffprober/parsers/json.rb:12:in `json'
	from /Library/Ruby/Gems/2.3.0/gems/ffprober-0.5.2/lib/ffprober/parser.rb:12:in `from_file'
	from (irb):5
	from /usr/bin/irb:11:in `<main>'
```

FFProbe version: 

```
ffprobe version git-2018-02-02-caaa40d Copyright (c) 2007-2018 the FFmpeg developers
built with Apple LLVM version 9.0.0 (clang-900.0.39.2)
configuration: --prefix=/usr/local/Cellar/ffmpeg/HEAD-caaa40d --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libfdk-aac --enable-libmp3lame --enable-libx264 --enable-libx265 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma --enable-nonfree
libavutil      56.  7.100 / 56.  7.100
libavcodec     58.  9.100 / 58.  9.100
libavformat    58.  7.100 / 58.  7.100
libavdevice    58.  0.101 / 58.  0.101
libavfilter     7. 11.101 /  7. 11.101
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  0.101 /  5.  0.101
libswresample   3.  0.101 /  3.  0.101
libpostproc    55.  0.100 / 55.  0.100
```

**Comment by beanieboi** [comment]
hey,

could you please paste to complete output? What error message is ffprobe presenting to you?
can you run ffprobe manually like this:

`ffprobe -v quiet -print_format json -show_format -show_streams -show_error /path/to/video.mkv`

thank you
ben

**Comment by roonieone** [comment]
Here's the full output:

``` ruby
irb(main):001:0> require 'ffprober'
=> true
irb(main):002:0> include Ffprober
=> Object
irb(main):003:0> Parser.from_file("/Users/orion/Downloads/Big Buck Bunny.mkv")
ffprobe version git-2018-02-02-caaa40d Copyright (c) 2007-2018 the FFmpeg developers
  built with Apple LLVM version 9.0.0 (clang-900.0.39.2)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/HEAD-caaa40d --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libfdk-aac --enable-libmp3lame --enable-libx264 --enable-libx265 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma --enable-nonfree
  libavutil      56.  7.100 / 56.  7.100
  libavcodec     58.  9.100 / 58.  9.100
  libavformat    58.  7.100 / 58.  7.100
  libavdevice    58.  0.101 / 58.  0.101
  libavfilter     7. 11.101 /  7. 11.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  0.101 /  5.  0.101
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100
[aac @ 0x7fd9b6003a00] This stream seems to incorrectly report its last channel as LFE[3], mapping to LFE[0]
Input #0, matroska,webm, from '/Users/orion/Downloads/Big Buck Bunny.mkv':
  Metadata:
    encoder         : libebml v0.7.7 + libmatroska v0.8.1
    creation_time   : 2009-01-05T17:04:20.000000Z
    TITLE           : Big Buck Bunny
    TITLE/URL       : http://www.bigbuckbunny.org
    ARTIST          : Peach Open Movie Team
    PRODUCER        : Ton Roosendaal
    COPYRIGHT       : (c) copyright Blender Foundation | www.bigbuckbunny.org
    TERMS_OF_USE    : Creative Commons Attribution 3.0 license
    TERMS_OF_USE/URL: http://creativecommons.org/licenses/by/3.0/
    COMMENT         : Encoded in DivX 7
  Duration: 00:09:56.52, start: 0.000000, bitrate: 7135 kb/s
    Stream #0:0(eng): Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080, SAR 1:1 DAR 16:9, 24 fps, 24 tbr, 1k tbn, 48 tbc (default)
    Metadata:
      title           : Main title
    Stream #0:1(eng): Audio: aac (LC), 48000 Hz, 5.1, fltp (default)
    Metadata:
      title           : English 5.1 Surround
    Stream #0:2(eng): Audio: aac (LC), 48000 Hz, stereo, fltp
    Metadata:
      title           : English Stereo
JSON::ParserError: A JSON text must at least contain two octets!
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:156:in `initialize'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:156:in `new'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:156:in `parse'
	from /Library/Ruby/Gems/2.3.0/gems/ffprober-0.5.2/lib/ffprober/parsers/json.rb:12:in `json'
	from /Library/Ruby/Gems/2.3.0/gems/ffprober-0.5.2/lib/ffprober/parser.rb:12:in `from_file'
	from (irb):3
	from /usr/bin/irb:11:in `<main>'
irb(main):004:0> 
```

> What error message is ffprobe presenting to you?

The error message is from ffprober in Ruby found in `json.rb`, not from ffprobe itself.

 > run ffprobe manually

```json
{
    "streams": [
        {
            "index": 0,
            "codec_name": "h264",
            "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
            "profile": "High",
            "codec_type": "video",
            "codec_time_base": "1/48",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "width": 1920,
            "height": 1080,
            "coded_width": 1920,
            "coded_height": 1080,
            "has_b_frames": 2,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "16:9",
            "pix_fmt": "yuv420p",
            "level": 40,
            "color_range": "tv",
            "color_space": "bt709",
            "color_transfer": "bt709",
            "color_primaries": "bt709",
            "chroma_location": "left",
            "field_order": "progressive",
            "refs": 1,
            "is_avc": "true",
            "nal_length_size": "4",
            "r_frame_rate": "24/1",
            "avg_frame_rate": "24/1",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "bits_per_raw_sample": "8",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "language": "eng",
                "title": "Main title"
            }
        },
        {
            "index": 1,
            "codec_name": "aac",
            "codec_long_name": "AAC (Advanced Audio Coding)",
            "profile": "LC",
            "codec_type": "audio",
            "codec_time_base": "1/48000",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "sample_fmt": "fltp",
            "sample_rate": "48000",
            "channels": 6,
            "channel_layout": "5.1",
            "bits_per_sample": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "language": "eng",
                "title": "English 5.1 Surround"
            }
        },
        {
            "index": 2,
            "codec_name": "aac",
            "codec_long_name": "AAC (Advanced Audio Coding)",
            "profile": "LC",
            "codec_type": "audio",
            "codec_time_base": "1/48000",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "sample_fmt": "fltp",
            "sample_rate": "48000",
            "channels": 2,
            "channel_layout": "stereo",
            "bits_per_sample": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "language": "eng",
                "title": "English Stereo"
            }
        }
    ],
    "format": {
        "filename": "/Users/orion/Downloads/Big Buck Bunny.mkv",
        "nb_streams": 3,
        "nb_programs": 0,
        "format_name": "matroska,webm",
        "format_long_name": "Matroska / WebM",
        "start_time": "0.000000",
        "duration": "596.522000",
        "size": "532054719",
        "bit_rate": "7135424",
        "probe_score": 100,
        "tags": {
            "encoder": "libebml v0.7.7 + libmatroska v0.8.1",
            "creation_time": "2009-01-05T17:04:20.000000Z",
            "TITLE": "Big Buck Bunny",
            "TITLE/URL": "http://www.bigbuckbunny.org",
            "ARTIST": "Peach Open Movie Team",
            "PRODUCER": "Ton Roosendaal",
            "COPYRIGHT": "(c) copyright Blender Foundation | www.bigbuckbunny.org",
            "TERMS_OF_USE": "Creative Commons Attribution 3.0 license",
            "TERMS_OF_USE/URL": "http://creativecommons.org/licenses/by/3.0/",
            "COMMENT": "Encoded in DivX 7"
        }
    }
}
```

**Comment by beanieboi** [comment]
The JSON parsing looks ok, ffprober can parse it and gives the correct information. I would love to have a look at the MKV file.
I couldn't find the MKV version of Big Buck Bunny over here (https://peach.blender.org/download/)
Where did you get the file from? Is it possible to send it over to me?

**Comment by roonieone** [comment]
Not entirely sure where I downloaded it from. May have been back when Blender offered an mkv version. Here's a [link to the one I am using to test](https://www.dropbox.com/s/cjaewq6qew3svht/Big%20Buck%20Bunny.mkv).

FWIW, I've tested it with mkvs, mp4s, h264, and h265 and they all produce this same error. The source file doesn't seem to effect the outcome.

**Comment by roonieone** [comment]
Just updated my Ruby version (`brew install ruby`) and got a different error or output. It seems like ffprober is feeding an empty string to the JSON parser (which might explain the [`JSON::ParserError: A JSON text must at least contain two octets!`](https://stackoverflow.com/questions/7200554/what-is-a-json-octet-and-why-are-two-required) error).

Full output:

```ruby
irb(main):001:0> require 'ffprober'
=> true
irb(main):002:0> include Ffprober
=> Object
irb(main):003:0> Parser.from_file("/Users/orion/Downloads/Big\ Buck\ Bunny.mkv")
ffprobe version git-2018-02-02-caaa40d Copyright (c) 2007-2018 the FFmpeg developers
  built with Apple LLVM version 9.0.0 (clang-900.0.39.2)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/HEAD-caaa40d --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libfdk-aac --enable-libmp3lame --enable-libx264 --enable-libx265 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma --enable-nonfree
  libavutil      56.  7.100 / 56.  7.100
  libavcodec     58.  9.100 / 58.  9.100
  libavformat    58.  7.100 / 58.  7.100
  libavdevice    58.  0.101 / 58.  0.101
  libavfilter     7. 11.101 /  7. 11.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  0.101 /  5.  0.101
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100
[aac @ 0x7ff4f782e400] This stream seems to incorrectly report its last channel as LFE[3], mapping to LFE[0]
Input #0, matroska,webm, from '/Users/orion/Downloads/Big Buck Bunny.mkv':
  Metadata:
    encoder         : libebml v0.7.7 + libmatroska v0.8.1
    creation_time   : 2009-01-05T17:04:20.000000Z
    TITLE           : Big Buck Bunny
    TITLE/URL       : http://www.bigbuckbunny.org
    ARTIST          : Peach Open Movie Team
    PRODUCER        : Ton Roosendaal
    COPYRIGHT       : (c) copyright Blender Foundation | www.bigbuckbunny.org
    TERMS_OF_USE    : Creative Commons Attribution 3.0 license
    TERMS_OF_USE/URL: http://creativecommons.org/licenses/by/3.0/
    COMMENT         : Encoded in DivX 7
  Duration: 00:09:56.52, start: 0.000000, bitrate: 7135 kb/s
    Stream #0:0(eng): Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080, SAR 1:1 DAR 16:9, 24 fps, 24 tbr, 1k tbn, 48 tbc (default)
    Metadata:
      title           : Main title
    Stream #0:1(eng): Audio: aac (LC), 48000 Hz, 5.1, fltp (default)
    Metadata:
      title           : English 5.1 Surround
    Stream #0:2(eng): Audio: aac (LC), 48000 Hz, stereo, fltp
    Metadata:
      title           : English Stereo
Traceback (most recent call last):
        6: from /usr/local/bin/irb:11:in `<main>'
        5: from (irb):3
        4: from /usr/local/lib/ruby/gems/2.5.0/gems/ffprober-0.5.2/lib/ffprober/parser.rb:12:in `from_file'
        3: from /usr/local/lib/ruby/gems/2.5.0/gems/ffprober-0.5.2/lib/ffprober/parsers/json.rb:12:in `json'
        2: from /usr/local/Cellar/ruby/2.5.0_1/lib/ruby/2.5.0/json/common.rb:156:in `parse'
        1: from /usr/local/Cellar/ruby/2.5.0_1/lib/ruby/2.5.0/json/common.rb:156:in `parse'
JSON::ParserError (765: unexpected token at '')
```

**Comment by beanieboi** [comment]
hey,

I spent some time trying to reproduce this but I was unable to do so. it works with my default ffmpeg installation (`brew install ffmpeg`) but according to your output you compiled ffmpeg on your own. is it possible that you miss some module? Maybe `ffprober` is picking up the wrong `ffprobe` binary (I assume you installed multiple?) `ffprober` will walk your `$PATH` and will pick the first binary it can find.

can you run `Ffprober::Ffmpeg::Finder.path` and make sure thats the correct `ffprobe` binary and that it is compiled with the correct flags.

in my case it picks the binary from the brew installation at `/usr/local/bin/ffprobe`

**Comment by roonieone** [comment]
> but according to your output you compiled ffmpeg on your own

I installed mine with Homebrew, using `brew install ffmpeg --with-x265 --with-fdk-aac --HEAD`. Homebrew may have had to compile its own version, but I didn't compile anything to install ffmpeg. 

> Maybe `ffprober` is picking up the wrong `ffprobe` binary (I assume you installed multiple?)

There is only one installed. Running `Ffprober::Ffmpeg::Finder.path` gives me `/usr/local/bin/ffprobe`.

**Comment by turanuzan** [comment]
C:\Users\MitWorks\Desktop\asdfsadf>vagrant up
C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/json/common.rb:156:in `initialize': negative string size (or size too big) (ArgumentError)
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/json/common.rb:156:in `new'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/json/common.rb:156:in `parse'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/json/common.rb:335:in `load'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/machine_index.rb:293:in `unlocked_reload'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/machine_index.rb:53:in `block in initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/machine_index.rb:323:in `block in with_index_lock'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/machine_index.rb:321:in `open'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/machine_index.rb:321:in `with_index_lock'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/machine_index.rb:52:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/environment.rb:724:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/environment.rb:724:in `machine_index'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/environment.rb:208:in `block in action_runner'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/runner.rb:33:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/environment.rb:526:in `hook'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/environment.rb:775:in `unload'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/bin/vagrant:167:in `ensure in <main>'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/bin/vagrant:167:in `<main>'

C:\Users\MitWorks\Desktop\asdfsadf>



ben böyle bir hata alıyorum nasıl çözebilirim

**Comment by turanuzan** [comment]
yardımcı olabilir misiniz
